import GoogleSvg from "@/components/svg/Google.svg";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-slate-200 flex flex-row justify-between px-5 py-1 items-center">
        <div>Viio Prueba Tecnica</div>
        <div className="flex flex-row items-center  cursor-pointer">
          <button onClick={() => router.push("/auth/singIn")}>Sing In</button>
        </div>
      </header>
    </>
  );
}
